<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SheepSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('sheep')->insert([
            [
                'eartag' => 'ET001',
                'gender' => 'male',
                'birth_date' => '2022-01-10',
                'eartag_color' => 'yellow',
                'breed_id' => 1,
                'sire_id' => null,
                'dam_id' => null,
                'cage_id' => 1,
                'status' => 'active',
                'created_at' => '2026-03-19 11:51:50',
                'updated_at' => '2026-03-19 11:51:50',
            ],
            [
                'eartag' => 'ET002',
                'gender' => 'female',
                'birth_date' => '2022-01-12',
                'eartag_color' => 'red',
                'breed_id' => 1,
                'sire_id' => null,
                'dam_id' => null,
                'cage_id' => 1,
                'status' => 'active',
                'created_at' => '2026-03-19 11:51:50',
                'updated_at' => '2026-03-19 11:51:50',
            ],
            [
                'eartag' => 'ET003',
                'gender' => 'male',
                'birth_date' => '2023-02-01',
                'eartag_color' => 'blue',
                'breed_id' => 1,
                'sire_id' => 1,
                'dam_id' => 2,
                'cage_id' => 2,
                'status' => 'active',
                'created_at' => '2026-03-19 11:51:50',
                'updated_at' => '2026-03-19 11:51:50',
            ],
            [
                'eartag' => 'ET004',
                'gender' => 'female',
                'birth_date' => '2023-02-05',
                'eartag_color' => 'green',
                'breed_id' => 1,
                'sire_id' => 1,
                'dam_id' => 2,
                'cage_id' => 2,
                'status' => 'active',
                'created_at' => '2026-03-19 11:51:50',
                'updated_at' => '2026-03-19 11:51:50',
            ],
            [
                'eartag' => 'ET005',
                'gender' => 'male',
                'birth_date' => '2023-03-10',
                'eartag_color' => 'yellow',
                'breed_id' => 2,
                'sire_id' => 1,
                'dam_id' => 2,
                'cage_id' => 3,
                'status' => 'active',
                'created_at' => '2026-03-19 11:51:50',
                'updated_at' => '2026-03-19 11:51:50',
            ],
            [
                'eartag' => 'ET006',
                'gender' => 'female',
                'birth_date' => '2023-03-12',
                'eartag_color' => 'red',
                'breed_id' => 2,
                'sire_id' => 1,
                'dam_id' => 2,
                'cage_id' => 3,
                'status' => 'active',
                'created_at' => '2026-03-19 11:51:50',
                'updated_at' => '2026-03-19 11:51:50',
            ],
            [
                'eartag' => 'ET007',
                'gender' => 'male',
                'birth_date' => '2023-04-01',
                'eartag_color' => 'blue',
                'breed_id' => 2,
                'sire_id' => 3,
                'dam_id' => 4,
                'cage_id' => 1,
                'status' => 'active',
                'created_at' => '2026-03-19 11:51:50',
                'updated_at' => '2026-03-19 11:51:50',
            ],
            [
                'eartag' => 'ET008',
                'gender' => 'female',
                'birth_date' => '2023-04-03',
                'eartag_color' => 'green',
                'breed_id' => 2,
                'sire_id' => 3,
                'dam_id' => 4,
                'cage_id' => 1,
                'status' => 'active',
                'created_at' => '2026-03-19 11:51:50',
                'updated_at' => '2026-03-19 11:51:50',
            ],
            [
                'eartag' => 'ET009',
                'gender' => 'male',
                'birth_date' => '2023-05-01',
                'eartag_color' => 'yellow',
                'breed_id' => 1,
                'sire_id' => 3,
                'dam_id' => 4,
                'cage_id' => 2,
                'status' => 'active',
                'created_at' => '2026-03-19 11:51:50',
                'updated_at' => '2026-03-19 11:51:50',
            ],
            [
                'eartag' => 'ET010',
                'gender' => 'female',
                'birth_date' => '2023-05-05',
                'eartag_color' => 'red',
                'breed_id' => 1,
                'sire_id' => 3,
                'dam_id' => 4,
                'cage_id' => 2,
                'status' => 'active',
                'created_at' => '2026-03-19 11:51:50',
                'updated_at' => '2026-03-19 11:51:50',
            ],
            [
                'eartag' => 'ET011',
                'gender' => 'male',
                'birth_date' => '2023-06-01',
                'eartag_color' => 'blue',
                'breed_id' => 1,
                'sire_id' => 5,
                'dam_id' => 6,
                'cage_id' => 3,
                'status' => 'active',
                'created_at' => '2026-03-19 11:51:50',
                'updated_at' => '2026-03-19 11:51:50',
            ],
            [
                'eartag' => 'ET012',
                'gender' => 'female',
                'birth_date' => '2023-06-03',
                'eartag_color' => 'green',
                'breed_id' => 1,
                'sire_id' => 5,
                'dam_id' => 6,
                'cage_id' => 3,
                'status' => 'active',
                'created_at' => '2026-03-19 11:51:50',
                'updated_at' => '2026-03-19 11:51:50',
            ],
            [
                'eartag' => 'ET013',
                'gender' => 'male',
                'birth_date' => '2023-07-01',
                'eartag_color' => 'yellow',
                'breed_id' => 2,
                'sire_id' => 5,
                'dam_id' => 6,
                'cage_id' => 1,
                'status' => 'active',
                'created_at' => '2026-03-19 11:51:50',
                'updated_at' => '2026-03-19 11:51:50',
            ],
            [
                'eartag' => 'ET014',
                'gender' => 'female',
                'birth_date' => '2023-07-04',
                'eartag_color' => 'red',
                'breed_id' => 2,
                'sire_id' => 5,
                'dam_id' => 6,
                'cage_id' => 1,
                'status' => 'active',
                'created_at' => '2026-03-19 11:51:50',
                'updated_at' => '2026-03-19 11:51:50',
            ],
            [
                'eartag' => 'ET015',
                'gender' => 'male',
                'birth_date' => '2023-08-01',
                'eartag_color' => 'blue',
                'breed_id' => 2,
                'sire_id' => 7,
                'dam_id' => 8,
                'cage_id' => 2,
                'status' => 'active',
                'created_at' => '2026-03-19 11:51:50',
                'updated_at' => '2026-03-19 11:51:50',
            ],
            [
                'eartag' => 'ET016',
                'gender' => 'female',
                'birth_date' => '2023-08-05',
                'eartag_color' => 'green',
                'breed_id' => 2,
                'sire_id' => 7,
                'dam_id' => 8,
                'cage_id' => 2,
                'status' => 'active',
                'created_at' => '2026-03-19 11:51:50',
                'updated_at' => '2026-03-19 11:51:50',
            ],
            [
                'eartag' => 'ET017',
                'gender' => 'male',
                'birth_date' => '2023-09-01',
                'eartag_color' => 'yellow',
                'breed_id' => 1,
                'sire_id' => 7,
                'dam_id' => 8,
                'cage_id' => 3,
                'status' => 'active',
                'created_at' => '2026-03-19 11:51:50',
                'updated_at' => '2026-03-19 11:51:50',
            ],
            [
                'eartag' => 'ET018',
                'gender' => 'female',
                'birth_date' => '2023-09-03',
                'eartag_color' => 'red',
                'breed_id' => 1,
                'sire_id' => 7,
                'dam_id' => 8,
                'cage_id' => 3,
                'status' => 'active',
                'created_at' => '2026-03-19 11:51:50',
                'updated_at' => '2026-03-19 11:51:50',
            ],
            [
                'eartag' => 'ET019',
                'gender' => 'male',
                'birth_date' => '2023-10-01',
                'eartag_color' => 'blue',
                'breed_id' => 1,
                'sire_id' => 9,
                'dam_id' => 10,
                'cage_id' => 1,
                'status' => 'active',
                'created_at' => '2026-03-19 11:51:50',
                'updated_at' => '2026-03-19 11:51:50',
            ],
            [
                'eartag' => 'ET020',
                'gender' => 'female',
                'birth_date' => '2023-10-04',
                'eartag_color' => 'green',
                'breed_id' => 1,
                'sire_id' => 9,
                'dam_id' => 10,
                'cage_id' => 1,
                'status' => 'active',
                'created_at' => '2026-03-19 11:51:50',
                'updated_at' => '2026-03-19 11:51:50',
            ],
        ]);
    }
}
